name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Build project
      run: lein with-profile prod uberjar
    - name: DockerHub build
      run: docker build . --file Dockerfile --tag told-it:$(date +%s)
    - name: DockerHub Publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ikshitijsingh/told-it
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Gcloud Docker image
      run: |
          docker build . --tag eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}/${{ github.ref }}
    - name: Authenticate into Google Cloud Platform
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCLOUD_EMAIL }}
        service_account_key: ${{ secrets.GCLOUD_AUTH }}

    - name: Configure Docker to use Google Cloud Platform
      run: "gcloud auth configure-docker --quiet"

    - name: Push image to Google Cloud Container Registry
      run: docker push eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}/${{ github.ref }}

    - name: Install beta commands and deploy on cloud run
      run: |
        gcloud components install beta --quiet
        gcloud beta run deploy ${{ secrets.GCLOUD_APP_NAME }} --quiet --image eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}/${{ github.ref }} --project ${{ secrets.GCLOUD_PROJECT }} --region europe-west1 --platform managed
