name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Build project
      run: lein with-profile prod uberjar
    - name: DockerHub build
      run: docker build . --file Dockerfile --tag namelss:$(date +%s)
    - name: DockerHub Publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ikshitijsingh/namelss
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
